### ISSUE TITLE
mqtt.createClient seems to be already gone from the mqtt library

### ISSUE THREAD

**Issue by indrasantosa** [MichielvdVelde/Adhesion#2]
Hey I notice that mqtt.createClient seems to be already gone from the mqtt library that cause an error when a user is trying to connect to the server.
The code should be updated. I can create a pull request if you need one.

**Comment by MichielvdVelde** [comment]
Hey, thanks for the issue. I don't actually update this repo anymore, it has been superceeded by [adhesion-server](https://github.com/MichielvdVelde/adhesion-server) and [adhesion-web-client](https://github.com/MichielvdVelde/adhesion-server).

I would accept a PR, should you decide to do one. :)

**Comment by indrasantosa** [comment]
Hi Michael,
I see, no worries then. I dont think it is required then :) great work btw.

Get Outlook for iOS




On Fri, Nov 11, 2016 at 2:50 AM +0800, "Michiel van der Velde" <notifications@github.com> wrote:












Hey, thanks for the issue. I don't actually update this repo anymore, it has been superceeded by adhesion-server and adhesion-web-client.



I would accept a PR, should you decide to do one. :)

**Comment by MichielvdVelde** [comment]
Thanks for mentioning it anyway. I may edit the mqtt portion sometime, if and when I feel it's needed. Until then, this issue is closed :)

**Comment by indrasantosa** [comment]
Great! Looking forward to it.. :)
